spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          client-app:
            provider: spring
            client-id: client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:4200/authorized
            scope:
              - openid
            client-name: client
        provider:
          spring:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/ms-users/**
          filters:
            - StripPrefix=1
        - id: ms-private-area
          uri: lb://ms-private-area
          predicates:
            - Path=/ms-private-area/**
          filters:
            - StripPrefix=1
        - id: ms-free-area
          uri: lb://ms-free-area
          predicates:
            - Path=/ms-free-area/**
          filters:
            - StripPrefix=1
        - id: ms-auth-server
          uri: http://localhost:9000
          predicates:
            - Path=/ms-auth-server/**
          filters:
            - StripPrefix=1
        - id: ms-api-ext
          uri: lb://ms-api-ext
          predicates:
            - Path=/ms-api-ext/**
          filters:
            - StripPrefix=1
        - id: ms-consumer
          uri: lb://ms-consumer
          predicates:
            - Path=/ms-consumer/**
          filters:
            - StripPrefix=1
        - id: ms-producer
          uri: lb://ms-producer
          predicates:
            - Path=/ms-producer/**
          filters:
            - StripPrefix=1
        - id: ms-resource-server
          uri: lb://ms-resource-server
          predicates:
            - Path=/ms-resource-server/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka